/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.akitta.snomed.ecl.ui.tests;

import com.google.inject.Injector;
import org.akitta.snomed.ecl.ui.internal.EclActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class EclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EclActivator.getInstance().getInjector("org.akitta.snomed.ecl.Ecl");
	}

}
