/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.akitta.snomed.ecl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EclRuntimeModule extends AbstractEclRuntimeModule {
}
