/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.akitta.snomed.ecl.ui;

import com.google.inject.Injector;
import org.akitta.snomed.ecl.ui.internal.EclActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EclExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EclActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EclActivator.getInstance().getInjector(EclActivator.ORG_AKITTA_SNOMED_ECL_ECL);
	}
	
}
